#!/bin/bash

# checking for mosh
if [ -e /usr/bin/mosh ]
then
    MOSH="/usr/bin/mosh"
else
    echo "/usr/bin/mosh does not exist"
    echo "Exiting now…"
    exit 0
fi

# checking for awk
if [ -e /usr/bin/awk ]
then
    AWK="/usr/bin/awk"
else
    echo "/usr/bin/awk does not exist"
    echo "Exiting now…"
    exit 0
fi

# checking for arguments
if [ -z "$1" ]
then
    echo "no argument found"
    echo "Exiting now…"
    exit 0
fi


# searching searching infos about requested host :
infos="$($AWK '/\y'$1'\y/ {for(i=1; i<=4; i++) {getline; print}}' $HOME/.ssh/config)"

# if no infos, then no matching host available
if [ -z "$infos" ]
then 
    echo "No host $1 found in $HOME/.ssh/config"
    exit
fi


# defining variables udp, hostname, $user and port
udp="$( echo $infos | $AWK '{ for (i=1;i<=NF;i++) { if( $i=="#Udp") { i++ ; print $i; } } } ' )"
port="$( echo $infos | $AWK '{ for (i=1;i<=NF;i++) { if( $i=="Port") { i++ ; print $i; } } } ' )"
user="$( echo $infos | $AWK '{ for (i=1;i<=NF;i++) { if( $i=="User") { i++ ; print $i; } } } ' )"
hostname="$( echo $infos | $AWK '{ for (i=1;i<=NF;i++) { if( $i=="Hostname") { i++ ; print $i; } } } ' )"

#if udp isn't defined, use default mosh configuration (first udp port available begining at 60000)
if [ -z "$udp" ]
then
    $MOSH --predict=always --ssh="ssh -p $port" $user@$hostname
else
    $MOSH -p $udp --predict=always --ssh="ssh -p $port" $user@$hostname
fi

exit 0
