#!/bin/bash

testDir(){
    if [ ! -d "$homeDir/Images/screenshots" ]
    then
        mkdir $homeDir/Images/screenshots
    fi
    if [ ! -d "$homeDir/Images/screenshots/GIF" ]
    then
        mkdir $homeDir/Images/screenshots/GIF
    fi
    if [ ! -d "$homeDir/Images/screenshots/GIF/tmp" ]
    then
        mkdir $homeDir/Images/screenshots/GIF/tmp
    fi
    if [ ! -d "$homeDir/Images/screenshots/GIF/tmp/output" ]
    then
        mkdir $homeDir/Images/screenshots/GIF/tmp/output
    fi
    content=$(ls -a $homeDir/Images/screenshots/GIF/tmp/output/ | sed -e "/\.$/d" | wc -l)
    if [ ! $content -eq 0 ]; then
        rm $homeDir/Images/screenshots/GIF/tmp/output/*
    fi
}

testSoft(){
    if [ -e /usr/bin/xrandr ]
    then
        XRANDR="/usr/bin/xrandr"
    else
        echo "/usr/bin/xrandr does not exist"
        exit 0
    fi
    if [ -e /usr/bin/ffmpeg ]
    then
        FFMPEG="/usr/bin/ffmpeg"
    else 
        echo "/usr/bin/ffmpeg does not exist. Please install ffmpeg"
        exit 0
    fi
    if [ -e /usr/bin/convert ]
    then                                                                                      
        CONVERT="/usr/bin/convert"
    else
        echo "/usr/bin/convert does not exist. Please install imagemagick"
        exit 0
    fi    
    if [ -e /usr/bin/xdg-open ]
    then
        XDG="/usr/bin/xdg-open"
    else
        echo "/usr/bin/xdg-open does not exist"
        exit 0
    fi    
}

captoreso(){
    x=$($XRANDR --current | grep '*+' | uniq | awk '{print $1}' |  cut -d 'x' -f1)
    y=$($XRANDR --current | grep '*+' | uniq | awk '{print $1}' |  cut -d 'x' -f2)
    resolution=$"$x*$y"
}
 
creaPng(){
    captoreso
    $FFMPEG -framerate 5 -f x11grab -video_size $resolution -i :0.0 -r 5 -q:v 1 $homeDir/Images/screenshots/GIF/tmp/output/image-%05d.png
}
 
geneGif(){
    $CONVERT $homeDir/Images/screenshots/GIF/tmp/output/* $homeDir/Images/screenshots/GIF/tmp/output.gif
    NOW=$(date +%m-%d-%Y-%T)
    $CONVERT -delay 20x100 $homeDir/Images/screenshots/GIF/tmp/output.gif $homeDir/Images/screenshots/GIF/tmp/slow.gif
    $CONVERT $homeDir/Images/screenshots/GIF/tmp/slow.gif -fuzz 10% -layers Optimize $homeDir/Images/screenshots/GIF/"$NOW-capture.gif"
    rm -R $homeDir/Images/screenshots/GIF/tmp
}
 
modifs(){
    read -p "Pictures will be merged into a GIF after validation. You can now cut undesirable parts if you delete concerned pictures. Do you want to ? yes/no : " answer
    until [ $answer == 'yes' ] || [ $answer == 'y' ] || [ $answer == 'no' ] || [ $answer == 'n' ]
    do 
        read -p "Invalid answer. Do you want to delete some parts ? yes/no  " answer
    done
    if [ $answer == 'yes' ] || [ $answer == 'y' ] 
    then
        $XDG $homeDir/Images/screenshots/GIF/tmp/output
        until [ "$TRMN" == "yes" ] || [ "$TRMN" == "y" ]
        do 
            read -p "Have you finished ? yes/no : " TRMN
        done
        geneGif
    else
        geneGif
    fi
}
 
user=$(whoami)
homeDir=$HOME
testDir
testSoft
creaPng
modifs 
