#!/bin/bash

if [ -e /usr/bin/xrandr ] 
then
    xr="/usr/bin/xrandr"
else
    echo "/usr/bin/xrander does not exist"
    exit 0
fi

if [ -z $1 ] || [ -z $2 ]
then
    echo "Missing options. Check out for the right syntax."
    echo "screenmgr [action] [device] [position]" 
    echo "action : -a | --add | -d | --disconnect"
    echo "device : -h | --hdmi | -v | --vga"                                                               
    echo "position : -r | --right | -l | --left | -c | --clone"  
    exit 0
fi

for i in $@
do
case $i in
    -a|--add)
        action="auto"
        ;;
    -d|--disconnect)
        action="off"
        ;;
    -v|--vga)
        device="VGA1"
        ;;
    -h|--hdmi)
        device="HDMI2"
        ;;
    -l|--left)
        position="left-of"
        ;;
    -r|--right)
        position="right-of"
        ;;
    -c|--clone)
        position="same-as"
        ;;
    *)
        echo "Unrecognized option. Check out for the right syntax."
        echo "screenmgr [action] [device] [position]"
        echo "action : -a | --add | -d | --disconnect"
        echo "device : -h | --hdmi | -v | --vga"
        echo "position : -r | --right | -l | --left | -c | --clone"
        exit 0
        ;;
esac
done

if [ $action == "off" ]
then
    $xr --output $device --$action
    exit 0
else
    if [ -z $position ]
    then
        position="same-as"
    fi
    $xr --output $device --$action --$position LVDS1
    exit 0
fi
